# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
