# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20170609_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=255)),
                ('more_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseDuration'),
        ),
    ]
