# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursesubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
