# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_choice', models.CharField(choices=[('T', 'Thoery'), ('P', 'Practical')], max_length=2)),
                ('subject_code', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='coursesubject',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseSubject',
        ),
    ]
