# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_subject_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='max_mark',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='min_mark',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
