# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170728_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
