# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_centercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='centercourse',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centercourse',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centercourse',
            name='date_registered',
            field=models.DateField(auto_now=True),
        ),
    ]
